* Copy and Paste
For the rest of the setup, you have the option of copying from this page, and pasting into your ssh session.
   - Mac:
     - Edit->Copy (command-C)
     - Edit->Paste (command-V)
   - Windows: http://www.chiark.greenend.org.uk/~sgtatham/putty/faq.html#faq-cutpaste
* Pulling the Docker Image
Run the following command at your terminal, and hit enter:

  #+begin_src sh
docker pull granek/jupyter-microbiome
  #+end_src

   This may take a few minutes to download and extract the docker image.  Once it is done it should say:
  #+begin_src sh
Status: Downloaded newer image for granek/jupyter-microbiome:latest
  #+end_src
* Downloading Notebooks
** First Time
   If this is your time following these instructions for your VM, run the following command to download the workshop notebooks from Github.  If you have already run this command before, skip this step and continue with [[Updating Notebooks]] below
  #+begin_src sh
   git clone https://github.com/granek/microbiome_workshop.git
  #+end_src
* Updating Notebooks
  Run the following to be sure that you have up-to-date Jupyter Notebooks
  #+begin_src sh
cd microbiome_workshop
git pull
  #+end_src
* Running Jupyter
   Next run the following command to launch Jupyter within a Docker Container.  You can (and probably should) change the password. This is the password for your Jupyter notebook.  You can use the same password that you used for your VM, but you don't have to.
  #+begin_src sh
docker run -d -p 8888:8888 -e PASSWORD="MyPasswordIsASecret" -e USE_HTTPS=yes --name jupyter1 -v $HOME/microbiome_workshop:/home/jovyan/work granek/jupyter-microbiome start-notebook.sh
  #+end_src

# docker run -d -p 8888:8888 -e PASSWORD="MyPasswordIsASecret" -e USE_HTTPS=yes --name jupyter1 -v $HOME/microbiome_workshop:/home/jovyan/work jupyter/r-notebook start-notebook.sh

* Opening Jupyter in a web browser
If everything worked, you should now have a Jupyter server running on your virtual machine, in which case you can access it through Chrome:
1. Open the URL https://DNS_name:8888/ in Chrome, substituting the DNS name from your Azure Dashboard (Note: be sure to include the "s" in "https").
2. It is safe to ignore the scary warning that starts: "Your connection is not private . . .". You are getting this message because we are not using a signed SSL certificate. 
3. Click on "ADVANCED"
4. Click on "Proceed to HOSTNAME.cloudapp.net (unsafe)"
5. Enter your *Jupyter Password* (the one you supplied to the "docker run" command
6. Your Jupyter Home Page should be now open showing several files and directories.  Click on "workshop_overview.ipynb" to open this notebook, which provides links to different components of the Workshop
7. In the Workshop Overview notebook, click on the "Update Notebooks" link and follow the directions there.
8. All of the computing for the workshop will take place within Jupyter, through your webbrowser.  When you are done with a Jupyter session, it is a good idea to [[vm_pause.org][Pause Your VM]].
#  https://mcaw1.cloudapp.net:8888/tree
* Next Step
Once you have confirmed that you can access your Jupyter notebook, and are done using it for the time being, it is a good idea to [[vm_pause.org][Pause Your VM]].

