Microsoft keeps the meter running while the VM is running. To stretch your VM dollars, it is a good idea to pause your VM when you are not going to be using it for a while.  The following steps tell you how to do that. Note that Microsoft also charges for storage that you are using, so the meter runs somewhat on a paused VM.
* TODO Stop Docker
This step is not strickly necessary, but it will allow us to pull image updates the next time.  Run the following in your *SSH Session*
  #+begin_src sh
docker stop jupyter1
docker rm jupyter1
  #+end_src
* TODO Pause VM
To pause your VM
1. Click *Virtual machines (classic)* in the left sidebar of https://portal.azure.com/.
2. Click on your VM in the list of VMs (unless you have been exploring there should only be one).
3. Click on the *Stop* button near the top of the panel.  This puts your VM in "suspended animation", saving the state of the VM, without using compute cycles
4. When you are ready to use your VM again, return to this panel and click *Start*
5. Then go back to [[start_jupyter.org][Start Jupyter]]
   
